[package]
name = "project-euler-rust"
version = "0.1.0"
authors = ["Marc Carr√© <carre.marc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-integer = "0.1.*"
